CREATE TABLE posts (
    -- The unique ID of the post
    id INT PRIMARY KEY,
    
    -- Links to the ID in the users table
    user_id INT NOT NULL,
    
    -- Title of the post
    title VARCHAR(255),
    
    -- Content of the post
    body TEXT,
    
    -- Metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO posts (id, user_id, title, body) VALUES
(1, 1, 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'),
(2, 1, 'qui est esse', 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'),
(3, 1, 'ea molestias quasi exercitationem repellat qui ipsa sit aut', 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'),
(4, 1, 'eum et est occaecati', 'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit'),
(5, 1, 'nesciunt quas odio', 'repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatem quasi\net iusto eveniet natus non quas delectus'),
(6, 1, 'dolorem eum magni eos aperiam quia', 'ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et nam ipsum suavit'),
(7, 1, 'magnam facilis autem', 'dolore placeat quibusdam ea quo vitae\nquibusdaum unde hic וגו'),
(8, 1, 'dolorem dolore est eligendi et totam', 'dignissimos aperiam sed eos et qui labore et velit aut'),
(9, 1, 'nesciunt iure omnis dolor tempora et accusantium', 'consectetur animi nesciunt iure dolore enim quia ad'),
(10, 1, 'optio molestias id quia eum', 'quo et expedita modi cum officia vel magni'),
(11, 2, 'et ea vero quia laudantium autem', 'delectus reiciendis molestiae occaecati non minima eveniet'),
(12, 2, 'in quibusdam tempore odit est aut', 'itaque id aut magnam praesentium quia et'),
(13, 2, 'dolorum ut in voluptas mollitia et quasi quo', 'autem mlanditiis sunt cupiditate nihil'),
(14, 2, 'voluptatem eligendi optio', 'fuga et accusamus dolorum perferendis'),
(15, 2, 'eveniet quod temporibus', 'reprehenderit quos placeat velit minima'),
(16, 2, 'sint suscipit perspiciatis velit dolorum rerum ipsa', 'iste id quae corporis mlanditiis totam'),
(17, 2, 'fugit mlanditiis ad et mlanditiis optio', 'velit ut ut sit mlanditiis'),
(18, 2, 'voluptate et itaque vero tempora molestiae', 'eveniet veritatis aut suscipit'),
(19, 2, 'adipisci placeat illum aut reiciendis qui', 'illum quis cupiditate quibusdaum'),
(20, 2, 'doloribus ad provident saepe pullum', 'qui consequuntur cumque et'),
(21, 3, 'asperiores ea ipsam voluptatibus modi tenetur', 'repellat aliquid praesentium dolorem quo'),
(22, 3, 'dolor sint quo a velit explicabo quia aut', 'eos qui et ipsum ipsam'),
(23, 3, 'maxime id vitae nihil numquam', 'veritatis ea ut tempora non'),
(24, 3, 'autem hic labore sunt dolores incidunt', 'enim et ex mlanditiis'),
(25, 3, 'rem alias distinctio quo quis', 'ullam consequatur ut omnis'),
(26, 3, 'est et quae odit qui non', 'similique esse doloribus'),
(27, 3, 'quasi id et eos tenetur aut quo autem', 'eum sed tempora quibusdaum'),
(28, 3, 'delectus ullam et mlanditiis et error', 'nobis quasi et mlanditiis'),
(29, 3, 'iusto eius quod iusto neque canaecati', 'odit magnam ut quidem'),
(30, 3, 'a aliquid sunt voluptatem minus', 'quoמ נתונים נוספים...'),
(31, 4, 'ullam ut expedita sunt mlanditiis facilis', 'debitis eius sed sit ut'),
(32, 4, 'doloremque illum aliquid sunt', 'deserunt eos nobis asperiores'),
(33, 4, 'qui explicabo illum mlanditiis ut', 'rerum ut et qui...'),
(34, 4, 'magnam ut mlanditiis mlanditiis', 'nihil ut mlanditiis...'),
(35, 4, 'id nam aspernatur occaecati', 'recusandae autמ...'),
(36, 4, 'fuga nam accusamus', 'quae etמ...'),
(37, 4, 'provident occaecati', 'etמ...'),
(38, 4, 'explicabo etמ', 'etמ...'),
(39, 4, 'eos וגו', 'וגו'),
(40, 4, 'enim וגו', 'וגו'),
(41, 5, 'non וגו', 'וגו'),
(42, 5, 'וגו', 'וגו'),
(43, 5, 'וגו', 'וגו'),
(44, 5, 'וגו', 'וגו'),
(45, 5, 'וגו', 'וגו'),
(46, 5, 'וגו', 'וגו'),
(47, 5, 'וגו', 'וגו'),
(48, 5, 'וגו', 'וגו'),
(49, 5, 'וגו', 'וגו'),
(50, 5, 'וגו', 'וגו'),
(51, 6, 'וגו', 'וגו'),
(52, 6, 'וגו', 'וגו'),
(53, 6, 'וגו', 'וגו'),
(54, 6, 'וגו', 'וגו'),
(55, 6, 'וגו', 'וגו'),
(56, 6, 'וגו', 'וגו'),
(57, 6, 'וגו', 'וגו'),
(58, 6, 'וגו', 'וגו'),
(59, 6, 'וגו', 'וגו'),
(60, 6, 'וגו', 'וגו'),
(61, 7, 'וגו', 'וגו'),
(62, 7, 'וגו', 'וגו'),
(63, 7, 'וגו', 'וגו'),
(64, 7, 'וגו', 'וגו'),
(65, 7, 'וגו', 'וגו'),
(66, 7, 'וגו', 'וגו'),
(67, 7, 'וגו', 'וגו'),
(68, 7, 'וגו', 'וגו'),
(69, 7, 'וגו', 'וגו'),
(70, 7, 'וגו', 'וגו'),
(71, 8, 'וגו', 'וגו'),
(72, 8, 'וגו', 'וגו'),
(73, 8, 'וגו', 'וגו'),
(74, 8, 'וגו', 'וגו'),
(75, 8, 'וגו', 'וגו'),
(76, 8, 'וגו', 'וגו'),
(77, 8, 'וגו', 'וגו'),
(78, 8, 'וגו', 'וגו'),
(79, 8, 'וגו', 'וגו'),
(80, 8, 'וגו', 'וגו'),
(81, 9, 'וגו', 'וגו'),
(82, 9, 'וגו', 'וגו'),
(83, 9, 'וגו', 'וגו'),
(84, 9, 'וגו', 'וגו'),
(85, 9, 'וגו', 'וגו'),
(86, 9, 'וגו', 'וגו'),
(87, 9, 'וגו', 'וגו'),
(88, 9, 'וגו', 'וגו'),
(89, 9, 'וגו', 'וגו'),
(90, 9, 'וגו', 'וגו'),
(91, 10, 'וגו', 'וגו'),
(92, 10, 'וגו', 'וגו'),
(93, 10, 'וגו', 'וגו'),
(94, 10, 'וגו', 'וגו'),
(95, 10, 'וגו', 'וגו'),
(96, 10, 'וגו', 'וגו'),
(97, 10, 'וגו', 'וגו'),
(98, 10, 'וגו', 'וגו'),
(99, 10, 'וגו', 'וגו'),
(100, 10, 'at nam consequatur ea', 'וגו');