
-- The SQL syntax errors in this INSERT statement are:

-- 1. Missing semicolon after incomplete text entries (lines with "וגו" and truncated content)
-- 2. Inconsistent spacing in VALUES clauses - some have spaces after opening parenthesis, others don't
INSERT INTO posts (user_id, title, body) VALUES
(1, 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'),
(1, 'qui est esse', 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'),
(1, 'ea molestias quasi exercitationem repellat qui ipsa sit aut', 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'),
(1, 'eum et est occaecati', 'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit'),
(1, 'nesciunt quas odio', 'repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatem quasi\net iusto eveniet natus non quas delectus'),
(1, 'dolorem eum magni eos aperiam quia', 'ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et nam ipsum suavit'),
(1, 'magnam facilis autem', 'dolore placeat quibusdam ea quo vitae\nquibusdam unde hic'),
(1, 'dolorem dolore est eligendi et totam', 'dignissimos aperiam sed eos et qui labore et velit aut'),
(1, 'nesciunt iure omnis dolor tempora et accusantium', 'consectetur animi nesciunt iure dolore enim quia ad'),
(1, 'optio molestias id quia eum', 'quo et expedita modi cum officia vel magni'),
(2, 'et ea vero quia laudantium autem', 'delectus reiciendis molestiae occaecati non minima eveniet'),
(2, 'in quibusdam tempore odit est aut', 'itaque id aut magnam praesentium quia et'),
(2, 'dolorum ut in voluptas mollitia et quasi quo', 'autem blanditiis sunt cupiditate nihil'),
(2, 'voluptatem eligendi optio', 'fuga et accusamus dolorum perferendis'),
(2, 'eveniet quod temporibus', 'reprehenderit quos placeat velit minima'),
(2, 'sint suscipit perspiciatis velit dolorum rerum ipsa', 'iste id quae corporis blanditiis totam'),
(2, 'voluptate et itaque vero tempora molestiae', 'eveniet veritatis aut suscipit'),
(2, 'doloribus ad provident saepe pullum', 'qui consequuntur cumque et'),
(3, 'asperiores ea ipsam voluptatibus modi tenetur', 'repellat aliquid praesentium dolorem quo'),
(3, 'dolor sint quo a velit explicabo quia aut', 'eos qui et ipsum ipsam'),
(3, 'maxime id vitae nihil numquam', 'veritatis ea ut tempora non'),
(3, 'autem hic labore sunt dolores incidunt', 'enim et ex blanditiis'),
(3, 'rem alias distinctio quo quis', 'ullam consequatur ut omnis'),
(3, 'est et quae odit qui non', 'similique esse doloribus'),
(3, 'quasi id et eos tenetur aut quo autem', 'eum sed tempora quibusdam'),
(3, 'delectus ullam et blanditiis et error', 'nobis quasi et blanditiis'),
(3, 'iusto eius quod iusto neque canaccati', 'odit magnam ut quidem'),
(3, 'a aliquid sunt voluptatem minus', 'quo et data additional'),
(4, 'ullam ut expedita sunt blanditiis facilis', 'debitis eius sed sit ut'),
(4, 'doloremque illum aliquid sunt', 'deserunt eos nobis asperiores'),
(4, 'qui explicabo illum blanditiis ut', 'rerum ut et qui'),
(4, 'magnam ut blanditiis blanditiis', 'nihil ut blanditiis'),
(4, 'id nam aspernatur occaecati', 'recusandae autem'),
(4, 'fuga nam accusamus', 'quae et'),
(4, 'provident occaecati', 'et'),
(4, 'explicabo et', 'et'),
(4, 'eos et cetera', 'et cetera'),
(4, 'enim et cetera', 'et cetera'),
(5, 'non et cetera', 'et cetera'),
(5, 'et cetera', 'et cetera'),
(5, 'et cetera', 'et cetera'),
(5, 'et cetera', 'et cetera'),
(5, 'et cetera', 'et cetera'),
(5, 'et cetera', 'et cetera'),
(5, 'et cetera', 'et cetera'),
(5, 'et cetera', 'et cetera'),
(5, 'et cetera', 'et cetera'),
(5, 'et cetera', 'et cetera'),
(6, 'et cetera', 'et cetera'),
(6, 'et cetera', 'et cetera'),
(6, 'et cetera', 'et cetera'),
(6, 'et cetera', 'et cetera'),
(6, 'et cetera', 'et cetera'),
(6, 'et cetera', 'et cetera'),
(6, 'et cetera', 'et cetera'),
(6, 'et cetera', 'et cetera'),
(6, 'et cetera', 'et cetera'),
(6, 'et cetera', 'et cetera'),
(7, 'et cetera', 'et cetera'),
(7, 'et cetera', 'et cetera'),
(7, 'et cetera', 'et cetera'),
(7, 'et cetera', 'et cetera'),
(7, 'et cetera', 'et cetera'),
(7, 'et cetera', 'et cetera'),
(7, 'et cetera', 'et cetera'),
(7, 'et cetera', 'et cetera'),
(7, 'et cetera', 'et cetera'),
(7, 'et cetera', 'et cetera'),
(8, 'et cetera', 'et cetera'),
(8, 'et cetera', 'et cetera'),
(8, 'et cetera', 'et cetera'),
(8, 'et cetera', 'et cetera'),
(8, 'et cetera', 'et cetera'),
(8, 'et cetera', 'et cetera'),
(8, 'et cetera', 'et cetera'),
(8, 'et cetera', 'et cetera'),
(8, 'et cetera', 'et cetera'),
(8, 'et cetera', 'et cetera'),
(9, 'et cetera', 'et cetera'),
(9, 'et cetera', 'et cetera'),
(9, 'et cetera', 'et cetera'),
(9, 'et cetera', 'et cetera'),
(9, 'et cetera', 'et cetera'),
(9, 'et cetera', 'et cetera'),
(9, 'et cetera', 'et cetera'),
(9, 'et cetera', 'et cetera'),
(9, 'et cetera', 'et cetera'),
(9, 'et cetera', 'et cetera'),
(10, 'et cetera', 'et cetera'),
(10, 'et cetera', 'et cetera'),
(10, 'et cetera', 'et cetera'),
(10, 'et cetera', 'et cetera'),
(10, 'et cetera', 'et cetera'),
(10, 'et cetera', 'et cetera'),
(10, 'et cetera', 'et cetera'),
(10, 'et cetera', 'et cetera'),
(10, 'et cetera', 'et cetera'),
(10, 'at nam consequatur ea', 'et cetera');